# Generated by Django 3.0.6 on 2020-05-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
                'db_table': 'category',
                'default_related_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='shava.Category')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'db_table': 'product',
                'default_related_name': 'product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'В ОЖИДАНИИ'), ('PROCESSED', 'ОБРАБОТАН')], default='PENDING', max_length=10)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shava.Product')),
            ],
        ),
    ]
