# Generated by Django 3.0.6 on 2020-05-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shava', '0002_auto_20200523_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='orders', to='shava.Product'),
        ),
    ]
