# Generated by Django 3.0.6 on 2020-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shava', '0003_auto_20200523_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders', to='shava.Product'),
        ),
    ]
