# Generated by Django 3.0.6 on 2020-05-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shava', '0004_auto_20200524_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
