# Generated by Django 3.0.6 on 2020-05-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shava', '0009_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sended',
            field=models.BooleanField(default=False),
        ),
    ]
