# Generated by Django 3.0.6 on 2020-05-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shava', '0010_order_is_sended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductcount',
            options={'default_related_name': 'order_product_counter'},
        ),
        migrations.AlterField(
            model_name='orderproductcount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_counter', to='shava.Order'),
        ),
        migrations.AlterField(
            model_name='orderproductcount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_counter', to='shava.Product'),
        ),
        migrations.AlterModelTable(
            name='orderproductcount',
            table='order_product_counter',
        ),
    ]
